-- Generated by drizzle-kit, then made safe for a table that already has rows.
--
-- What it produced was `ADD COLUMN … NOT NULL` with no default for slug,
-- status and version, which is a statement that cannot run on any
-- installation with one revision in it. The columns are added nullable,
-- backfilled from the document each revision belongs to, and only then
-- constrained. A revision written before this migration did not record those
-- fields; the document's current values are the closest true answer, and the
-- alternative — inventing a placeholder — would make a restore put a
-- fabricated slug on a live page.

ALTER TABLE "contents" ADD COLUMN "version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint

ALTER TABLE "content_revisions" ADD COLUMN "slug" text;--> statement-breakpoint
ALTER TABLE "content_revisions" ADD COLUMN "excerpt" text;--> statement-breakpoint
ALTER TABLE "content_revisions" ADD COLUMN "status" "content_status";--> statement-breakpoint
ALTER TABLE "content_revisions" ADD COLUMN "parent_id" uuid;--> statement-breakpoint
ALTER TABLE "content_revisions" ADD COLUMN "published_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "content_revisions" ADD COLUMN "version" integer;--> statement-breakpoint

UPDATE "content_revisions" AS r
SET "slug" = c."slug",
    "excerpt" = c."excerpt",
    "status" = c."status",
    "parent_id" = c."parent_id",
    "published_at" = c."published_at"
FROM "contents" AS c
WHERE c."id" = r."content_id";--> statement-breakpoint

-- Oldest first, so an existing history reads in the order it happened.
UPDATE "content_revisions" AS r
SET "version" = numbered."ordinal"
FROM (
  SELECT "id", row_number() OVER (PARTITION BY "content_id" ORDER BY "created_at") AS "ordinal"
  FROM "content_revisions"
) AS numbered
WHERE numbered."id" = r."id";--> statement-breakpoint

ALTER TABLE "content_revisions" ALTER COLUMN "slug" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "content_revisions" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "content_revisions" ALTER COLUMN "version" SET NOT NULL;--> statement-breakpoint

ALTER TABLE "content_revisions" ADD CONSTRAINT "content_revisions_parent_id_contents_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."contents"("id") ON DELETE set null ON UPDATE no action;
