-- Generated by drizzle-kit, then reordered and made safe for existing rows.
--
-- Two things were wrong with what it produced. It added the composite foreign
-- key before the unique constraint that key references, which Postgres
-- refuses. And it added both to a table whose rows may already violate them:
-- until now `parentId` only guaranteed that some row existed, so a page could
-- name a post, a translation in another language, or itself, and any of those
-- would make this migration fail halfway.
--
-- Incompatible parents are detached rather than deleted. A child whose parent
-- was the wrong kind of thing is still a real document; it becomes a root,
-- which is visible and recoverable, where deleting it would not be.

ALTER TABLE "content_revisions" DROP CONSTRAINT "content_revisions_parent_id_contents_id_fk";--> statement-breakpoint
ALTER TABLE "contents" DROP CONSTRAINT "contents_parent_id_contents_id_fk";--> statement-breakpoint

ALTER TABLE "contents" ADD CONSTRAINT "contents_id_type_locale_uq" UNIQUE("id","type","locale");--> statement-breakpoint

-- A parent of another type or another language, and a document that is its own
-- parent. Both were representable; neither is any more.
UPDATE "contents" AS child
SET "parent_id" = NULL
WHERE child."parent_id" IS NOT NULL
  AND (
    child."parent_id" = child."id"
    OR NOT EXISTS (
      SELECT 1 FROM "contents" AS parent
      WHERE parent."id" = child."parent_id"
        AND parent."type" = child."type"
        AND parent."locale" = child."locale"
    )
  );--> statement-breakpoint

-- Cycles among rows that survived the pass above. Walking from the roots marks
-- everything reachable; whatever is left has no root ancestor, which for a
-- tree means it is in a loop. Those are detached too — a document nothing can
-- reach the top from has no path, so it has no URL either.
WITH RECURSIVE reachable AS (
  SELECT "id" FROM "contents" WHERE "parent_id" IS NULL
  UNION ALL
  SELECT c."id" FROM "contents" c JOIN reachable r ON c."parent_id" = r."id"
)
UPDATE "contents"
SET "parent_id" = NULL
WHERE "parent_id" IS NOT NULL
  AND "id" NOT IN (SELECT "id" FROM reachable);--> statement-breakpoint

ALTER TABLE "contents" ADD CONSTRAINT "contents_parent_fk" FOREIGN KEY ("parent_id","type","locale") REFERENCES "public"."contents"("id","type","locale") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "contents" ADD CONSTRAINT "contents_parent_not_self" CHECK ("contents"."parent_id" is distinct from "contents"."id");--> statement-breakpoint
CREATE INDEX "contents_parent_idx" ON "contents" USING btree ("parent_id");
