import { sql } from 'drizzle-orm'
import {
  boolean,
  check,
  foreignKey,
  index,
  pgEnum,
  pgTable,
  primaryKey,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core'
import { contents } from './contents.ts'
import { media } from './media.ts'

/**
 * Which live documents use which assets, as rows the database can enforce.
 *
 * The references themselves live in JSONB — an image block names an asset, a
 * post's metadata names a featured one — and JSONB cannot carry a foreign key.
 * So a document could name an asset that had never existed, and deleting an
 * asset asked a question and then acted on the answer in a second transaction:
 * a save committing in between produced a reference to a row that was already
 * gone. Both halves were silent. The renderer drops a missing image, so the
 * loss showed up as an article with a hole in it and no error anywhere.
 *
 * These rows are what the database can hold to. `ON DELETE RESTRICT` refuses to
 * remove an asset a document still uses; the foreign key on `media_id` refuses
 * a row naming an asset that is not there. Whichever of the two commits first,
 * the other is refused rather than allowed to disagree with it.
 *
 * **Live state only.** There is no revision column and there will not be one:
 * with `content_id` alone this table cannot represent `content_revisions`, and
 * pretending otherwise would be worse than saying so. A revision keeps the
 * identifier it was written with, exactly as it keeps a `parentId` whose
 * document may since have gone; restoring one that names a deleted asset is
 * refused at the point of restoring, which is where somebody can act on it.
 */
export const contentMediaSource = pgEnum('content_media_source', ['block', 'meta'])

export const contentMedia = pgTable(
  'content_media',
  {
    contentId: uuid().notNull(),
    mediaId: uuid().notNull(),
    /** Where the reference was found. The block id and the metadata key are
     * not stored: they are produced by the extractor when a refusal has to
     * name a place, and nothing reads them from here. */
    source: contentMediaSource().notNull(),
  },
  (t) => [
    /*
     * One row per (document, asset, place). An asset used by three blocks of
     * one document is one row: the question this table answers is whether the
     * document uses it, not how many times.
     */
    primaryKey({ name: 'content_media_pkey', columns: [t.contentId, t.mediaId, t.source] }),

    /*
     * Named, both of them. The translation of a violation into an API refusal
     * reads the constraint name, and a name generated by the tooling is one
     * that can change under it without anything failing until production.
     */
    foreignKey({
      name: 'content_media_content_fk',
      columns: [t.contentId],
      foreignColumns: [contents.id],
    }).onDelete('cascade'),

    foreignKey({
      name: 'content_media_media_fk',
      columns: [t.mediaId],
      foreignColumns: [media.id],
    }).onDelete('restrict'),

    /*
     * PostgreSQL indexes the referenced side of a foreign key and not the
     * referencing side. `ON DELETE RESTRICT` interrogates the referencing
     * side, so without this every media deletion would scan this table.
     */
    index('content_media_media_idx').on(t.mediaId),
  ],
)

/**
 * Whether the relational mirror has been reconciled with the JSONB it mirrors.
 *
 * A schema migration and a reconciliation are two different events, and an
 * operator can perform the first without the second: apply the SQL, start the
 * new API, and it runs against an empty `content_media` — every asset
 * deletable, every reference unenforced, and nothing saying so.
 *
 * So the migration writes down which of the two states this installation is
 * in. A database that had documents when the table appeared is `pending` until
 * the reconciliation proves otherwise; one that was empty is `ready` from the
 * start, because there is nothing to mirror. The API refuses to start while it
 * is `pending` — one row read at boot, not a scan of every document.
 *
 * One row, and the check constraint is what keeps it that way: a table meant
 * to hold a single fact that quietly holds two is a fact nobody can read.
 */
export const mediaReferenceSyncState = pgEnum('media_reference_sync_state', ['pending', 'ready'])

export const mediaReferenceSync = pgTable(
  'media_reference_sync',
  {
    id: boolean().primaryKey().default(true),
    state: mediaReferenceSyncState().notNull(),
    reconciledAt: timestamp({ withTimezone: true }),
  },
  (t) => [check('media_reference_sync_single_row', sql`${t.id}`)],
)
